apiVersion: v1
kind: Service
metadata:
  name: etio
spec:
  selector:
    app.kubernetes.io/name: etio
  ports:
    - { name: otlp-grpc, port: 4317, targetPort: otlp-grpc, appProtocol: grpc }
    - { name: otlp-http, port: 4318, targetPort: otlp-http }
    - { name: api, port: 7070, targetPort: api }
